CREATE TABLE IF NOT EXISTS "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL,
    "HeadFullName" varchar(150) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Departments_Name" ON "Departments" ("Name");

CREATE TABLE IF NOT EXISTS "Doctors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" varchar(150) NOT NULL,
    "Specialty" varchar(100) NOT NULL,
    "OfficeNumber" varchar(20) NOT NULL,
    "Phone" varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Patients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" varchar(150) NOT NULL,
    "DateOfBirth" date NOT NULL,
    "Gender" integer NOT NULL,
    "Address" varchar(250) NOT NULL,
    "Phone" varchar(20) NOT NULL,
    "OmsPolicyNumber" varchar(30) NOT NULL,
    "Snils" varchar(14) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Patients_OmsPolicyNumber" ON "Patients" ("OmsPolicyNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Patients_Snils" ON "Patients" ("Snils");

CREATE TABLE IF NOT EXISTS "Appointments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AppointmentDateTime" timestamp without time zone NOT NULL,
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "Diagnosis" varchar(500) NOT NULL,
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Appointments_PatientId" ON "Appointments" ("PatientId");
CREATE INDEX IF NOT EXISTS "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Appointments_DoctorId_AppointmentDateTime" ON "Appointments" ("DoctorId", "AppointmentDateTime");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Appointments_PatientId_AppointmentDateTime" ON "Appointments" ("PatientId", "AppointmentDateTime");

CREATE TABLE IF NOT EXISTS "MedicalRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CardNumber" varchar(30) NOT NULL,
    "PatientId" integer NOT NULL,
    "CreatedDate" date NOT NULL,
    "DiseaseHistory" varchar(2000) NOT NULL,
    CONSTRAINT "FK_MedicalRecords_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MedicalRecords_CardNumber" ON "MedicalRecords" ("CardNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_MedicalRecords_PatientId" ON "MedicalRecords" ("PatientId");

